from preprocessing import preprocess_text

def search(query:str,inverted_index:dict) -> list:
    """
    Searches the inverted index for the given query and ranks documents.
    Parameters : query ( the user searched ) and inverted_index ( the dictionary generated by the indexer based on all the files texts )

    Returns : a list of tuples ( filename , score ) in a descending order based on the score 
    """

    # preprocessing the query as well 
    query_words = preprocess_text(query)

    #dictionary to store document scores 
    scores = {}

    # Loop up each query word in the inverted_index
    for word in query_words: # iterating words inside the query_words list 
        if word in inverted_index: # if the same word is in the inverted_index dictionary then go ahead 
            for filename in inverted_index[word]: # the inverted_index contains word as key and a set as a value so here filename is the elemnt traversed from that set 
                scores[filename] = scores.get(filename,0)+1
    
    # scores of filename ( key ) and the get(filename,0) means get the value of filename or put the default 0 if no value exists and increment the score by one because we found the matching query 

    # now scores is a dict : { str : int } ... { filename : score }

    # now ranking the file according to there scores in the descending order ( based on their scores ) 
    ranked_results = sorted(
            scores.items(),
            key = lambda item: item[1],
            reverse = True
        )
    
    # sorted and reverse = True means sorting in descending order 
    return ranked_results
    
